projects:
  spotify:
    schemaPath: 'F:/React Native Project/spotify/graphql/schema.json'
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
